services:
  agent-rust:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - SLO_ID=ServiceSLO
      - CONF_PARAM=ServiceParam
      - SLEEP_INTERVAL=120
      - SLO_MIN=24.0
      - SLO_MAX=30.0
      - PARAM_MIN=0
      - PARAM_MAX=16
      - PARAM_CORRELATION=1
      - PARAM_CHANGE=1
      - NUM_STEPS=120
      - API_HOST=http://localhost:8080/v0
    volumes:
      - ./Results:/results